version: '3.8'
services:
  dynamodb-local:
    networks:
      - backend
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./database:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    user: root
  angular-local:
    build: ./client
    ports:
      - "8080:80"

networks:
  backend:
    name: sam-backend