AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  systemDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: system
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema: 
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  namesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: names/
      Handler: names.handle
      Runtime: python3.8
      Events:
        namesApiEvent:
          Type: Api
          Properties:
            Path: /names
            Method: ANY
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref systemDB

# Globals:
#   Api:
#     Auth:
#       Authorizers:
#         MyCognitoAuth:
#           UserPoolArn:
#             Fn::GetAtt:
#               - MyCognitoUserPool
#               - Arn
