AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  namesDB:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: names
      PrimaryKey:
        Name: name
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  namesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: names/
      Handler: names.handle
      Runtime: python3.8
      Events:
        namesApiEvent:
          Type: Api
          Properties:
            Path: /names
            Method: ANY
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref namesDB

# Globals:
#   Api:
#     Auth:
#       Authorizers:
#         MyCognitoAuth:
#           UserPoolArn:
#             Fn::GetAtt:
#               - MyCognitoUserPool
#               - Arn
