AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  namesDB:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: names
      PrimaryKey:
        Name: name
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  namesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: names/
      Handler: names.handle
      Runtime: python3.8
      Events:
        namesApiEvent:
          Type: Api
          Properties:
            Path: /names
            Method: ANY
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref namesDB
  
  videoGensisAuthPostAuthentication:
    Type: AWS::Serverless::Function,
    Properties:
      CodeUri: auth/
      Handler: videoGensisAuthPostAuthentication.handle
      Runtime: nodejs14.x
      UserPool: us-west-2_3LjdLzhH5
      Trigger: PostAuthentication
        



# Globals:
#   Api:
#     Auth:
#       Authorizers:
#         MyCognitoAuth:
#           UserPoolArn:
#             Fn::GetAtt:
#               - MyCognitoUserPool
#               - Arn
